name: Plugin asset/readme update
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  update:
    uses: sy-records/.github/.github/workflows/wordpress-plugin-asset-update.yaml@main
    with:
      skip_assets: false
    secrets: inherit
