name: Deploy to WordPress.org
on:
  pull_request:
  release:
    types: [ published ]
jobs:
  deploy:
    uses: sy-records/.github/.github/workflows/wordpress-plugin-deploy.yaml@main
    with:
      build: true
      working-directory: sdk
      php: '7.1'
    secrets: inherit

  packaging:
    needs: deploy
    strategy:
      matrix:
        php: [ '8.0' ]
    uses: sy-records/.github/.github/workflows/wordpress-plugin-packaging.yaml@main
    with:
      build: true
      working-directory: sdk
      php: ${{ matrix.php }}
    secrets: inherit
